// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE, Channel } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Round-trip command: shell + core metadata for the placeholder page.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`] if the read through managed state fails.
	 */
	shellInfo: () => typedError<ShellInfo, BusError>(__TAURI_INVOKE("shell_info")),
	/**
	 *  A command that fails **on purpose**, so the error path is demonstrated rather than
	 *  asserted only in a unit test.
	 * 
	 *  The placeholder page invokes it and renders the resulting [`BusError`]. Keeping a
	 *  deliberate-failure command on the bus means the frontend's error rendering is
	 *  exercised by every developer who opens the app, not only when something breaks.
	 * 
	 *  # Errors
	 * 
	 *  Always. That is the point.
	 */
	busSelftestFailure: () => typedError<null, BusError>(__TAURI_INVOKE("bus_selftest_failure")),
	/**
	 *  Start the demo event stream on a **per-invocation** channel.
	 * 
	 *  The `channel` argument is the whole correlation mechanism: Tauri mints one per
	 *  `invoke`, so a second run cannot reach the first run's screen.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`] on a genuine failure; a dropped channel is reported as
	 *  `cancelled` in the [`StreamOutcome`], not as an error.
	 */
	startDemoStream: (steps: number, channel: Channel<BusEvent>) => typedError<StreamOutcome, BusError>(__TAURI_INVOKE("start_demo_stream", { steps, channel })),
	/**
	 *  Report which credential source would answer an LLM call, without exposing the
	 *  credential itself — the no-credential banner's read.
	 * 
	 *  This is `llm_credential_status`'s first production caller (`src/adapters/secrets.rs`
	 *  r1.s1.w2), which is what makes removing its `#[allow(dead_code)]` sound rather than
	 *  a bare grep of convenience: `deny(warnings)` would not let the allow come off before
	 *  a real caller existed.
	 * 
	 *  No `Result`: the read has no failure mode (an unresolvable credential reads as
	 *  [`CredentialStatus::None`], not an error), so wrapping it in one would claim a
	 *  failure mode this command does not have.
	 */
	credentialStatus: () => __TAURI_INVOKE<CredentialStatus>("credential_status"),
	/**
	 *  The Strategy Library's one read: every strategy, its version tree, per-version
	 *  stats where a persisted run exists, and each version's recent run catalog.
	 * 
	 *  A pure read — the Library writes nothing (ADR-0010); pin/archive/rename each
	 *  need a write command and are out of this item's budget.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`] if any repository read fails — including a corrupt
	 *  run row surfacing from the fail-closed `latest_run_for_version` (#39).
	 */
	libraryOverview: () => typedError<LibraryOverview, BusError>(__TAURI_INVOKE("library_overview")),
	/**
	 *  Compose a strategy from a natural-language target, streaming the composer's
	 *  tool-call steps over a **per-invocation** channel (grill A2 — the channel is
	 *  the correlation) until the run finalizes and a persisted, attributable
	 *  `StrategyVersion` exists.
	 * 
	 *  **Nothing but the target crosses the boundary in, and no credential crosses
	 *  it in any direction, ever** (ADR-0016, the risk gate's IPC half): the key
	 *  resolves INSIDE the ring via [`resolve_llm_api_key`], `key.expose()` reaches
	 *  exactly two consumers (the provider constructor and `Redactor::from_config`),
	 *  and the credential-source LABEL is captured before either — the live arm's
	 *  key discipline (`src/cli/compose.rs`), mirrored.
	 * 
	 *  An unresolvable credential is a [`BusError`] carrying the resolver's own
	 *  message — it names every searched location and fails closed (`w2`); the
	 *  screen renders it, and `w5`'s banner already states the condition globally.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`] on a config-load failure, an unresolvable credential,
	 *  or a genuine compose/persist failure. A dropped channel is reported as
	 *  `cancelled` in the [`ComposeResult`], not as an error.
	 */
	composeStrategy: (nlTarget: string, channel: Channel<BusEvent>) => typedError<ComposeResult, BusError>(__TAURI_INVOKE("compose_strategy", { nlTarget, channel })),
	/**
	 *  Cancel an in-flight compose run by id.
	 * 
	 *  The Designer fires this from its unmount cleanup. Without it, navigating away
	 *  mid-compose left the run streaming into a channel nobody read: the JavaScript
	 *  `Channel`'s callback stays registered with Tauri for the life of the webview, so
	 *  every send kept SUCCEEDING, the failed-send guard never tripped, and the
	 *  remaining billable LLM calls ran to completion and persisted a strategy the user
	 *  had already walked away from.
	 * 
	 *  Tripping the latch makes [`RefusingProvider`] refuse at the run's next model turn,
	 *  so the run stops within one LLM call and persists nothing.
	 * 
	 *  Returns whether a run by that id was in flight. `false` is an ordinary outcome —
	 *  the run may have finished between the frontend deciding to cancel and this command
	 *  arriving — not an error, so the Designer's cleanup needs no failure path.
	 * 
	 *  # Errors
	 * 
	 *  Never. The `Result` is the bus's uniform command shape.
	 */
	composeCancel: (runId: string) => typedError<boolean, BusError>(__TAURI_INVOKE("compose_cancel", { runId })),
	/**
	 *  `run_backtest_version` — the Backtest Lab's one command (r1.s3.w3).
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`]; see [`run_backtest_version_core`].
	 */
	runBacktestVersion: (request: BacktestRunRequest) => typedError<BacktestRunDto, BusError>(__TAURI_INVOKE("run_backtest_version", { request })),
	/**
	 *  `coach_turn` — start or reload one coach turn for a persisted run (r1.s4.w3).
	 * 
	 *  This wrapper is where the credential lives, exactly as [`compose_strategy`]'s
	 *  is: the config overlays load, the key resolves, the redactor and the provider
	 *  are built from it, and the core receives everything EXCEPT the key. It therefore
	 *  appears in no argument, no return value, no event, no error and no DTO, because
	 *  it never leaves this function (ADR-0016).
	 * 
	 *  The prompt and its version resolve together from the same bytes (audit C2), so
	 *  the ledger row's `prompt_version` is a true answer to "which prompt produced
	 *  this?" — including when an operator's `$PULSE_PROMPT_DIR/coach.md` overlay won.
	 * 
	 *  **The transport makes ONE attempt per turn** at the coach's own request timeout
	 *  ([`coach_provider`]), the same constructor `pulse coach` builds through: a turn
	 *  records one exchange and names one ledger row, and the retrying default would put
	 *  three upstream attempts and their cost behind that one record.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`] on a config-load failure, an unresolvable credential, a
	 *  live duplicate (`busy`), an absent run, or an unrecordable turn. A provider
	 *  TRANSPORT fault is not an error — it comes back as a recorded failed session.
	 */
	coachTurn: (request: CoachTurnRequestDto) => typedError<CoachSessionDto, BusError>(__TAURI_INVOKE("coach_turn", { request })),
	/**
	 *  `coach_decide` — modify, reject or accept one recorded proposal (r1.s4.w3).
	 * 
	 *  No credential, no provider and no config overlay: an accept re-runs the parent
	 *  run's exact persisted inputs through the real engine and asks the coach nothing,
	 *  so this wrapper is a thin adapter over the core and nothing else.
	 * 
	 *  # Errors
	 * 
	 *  Returns a [`BusError`]; see [`coach_decide_core`].
	 */
	coachDecide: (request: CoachDecisionRequestDto) => typedError<CoachDecisionDto, BusError>(__TAURI_INVOKE("coach_decide", { request })),
};

/* Types */
/**  The latest accept attempt's typed failure, when the most recent one failed. */
export type AcceptFailureDto = {
	/**  Where the accept stopped (`apply` / `load_inputs` / … / `persist`). */
	stage: string,
	/**  What went wrong, stated for the trader. */
	message: string,
	/**  What the failure is about, when it is about one thing. */
	subject: string | null,
};

/**  What one committed accept produced, as the side-by-side panel needs it. */
export type AcceptedCoachDto = {
	/**  The child version the accept minted. */
	childVersionId: string,
	/**  The re-backtest run OF that child. */
	acceptedRunId: string,
	/**  The PARENT run's persisted summary — the "before" half. */
	before: SummaryDto,
	/**
	 *  The CHILD run's persisted summary. Absent only for a saved-but-unreadable
	 *  child run, which is a read failure and not an accept failure.
	 */
	after: SummaryDto | null,
	/**  Whether that read back succeeded. */
	readBack: ReadBackDto,
};

/**
 *  The complete Backtest Lab response.
 * 
 *  `PartialEq` but not `Eq` — `sharpe`/`sortino` are `f64`, the same reason
 *  [`PersistedRun`] carries only `PartialEq`.
 */
export type BacktestRunDto = {
	/**  The freshly minted run id. Every invocation creates a new one. */
	runId: string,
	/**  The immutable version this run is attributed to. */
	strategyVersionId: string,
	/**  The run-row schema tag. */
	schemaVersion: number,
	/**  When the run was recorded (RFC3339 UTC, millisecond precision). */
	createdAt: string,
	/**  The pair the run consumed. */
	pair: string,
	/**  The primary timeframe, Binance interval text. */
	primaryTimeframe: string,
	/**  The exact immutable primary snapshot identity. */
	primaryDataVersion: string,
	/**  The HTF timeframe, when the run used one. Paired with the next field. */
	htfTimeframe: string | null,
	/**  The exact immutable HTF snapshot identity. */
	htfDataVersion: string | null,
	/**  First candle `open_time` of the **reloaded** primary snapshot, epoch ms. */
	firstOpenTimeMs: string,
	/**  Last candle `close_time` of the **reloaded** primary snapshot, epoch ms. */
	lastCloseTimeMs: string,
	/**  Starting equity, exact decimal string. */
	startingEquity: string,
	/**  Taker fee in basis points. */
	takerFeeBps: string,
	/**  Slippage in basis points. */
	slippageBps: string,
	/**  How funding was sourced (`snapshot_rates`). */
	funding: string,
	/**  The recording engine's build fingerprint. */
	engineFingerprint: string,
	/**  The recording engine's target triple. */
	engineTarget: string,
	/**  The stored integrity hash, re-derived and checked on read. */
	resultContentHash: string,
	/**
	 *  FR-7 warning from the pre-save comparison against the prior run.
	 * 
	 *  The one field not read back from storage — the comparison has no column and
	 *  must happen before the insert.
	 */
	fingerprintWarning: string | null,
	/**  Net P&L. */
	netPnl: string,
	/**  Total taker fees. */
	feesTotal: string,
	/**  Total signed funding. */
	fundingTotal: string,
	/**  Total adverse slippage. */
	slippageTotal: string,
	/**  Mean P&L per trade. */
	expectancy: string,
	/**  Fraction of trades that won. */
	winRate: string,
	/**  Gross profit over gross loss; `null` when there is no loss to divide by. */
	profitFactor: string | null,
	/**  Sum of winning P&L. */
	grossProfit: string,
	/**  Sum of losing P&L. */
	grossLoss: string,
	/**  Mean winning trade. */
	avgWin: string,
	/**  Mean losing trade. */
	avgLoss: string,
	/**  Largest peak-to-trough equity drop. */
	maxDrawdown: string,
	/**  Number of completed trades. */
	tradeCount: number,
	/**  How many won. */
	winCount: number,
	/**  How many lost. */
	lossCount: number,
	/**  Longest winning streak. */
	maxWinStreak: number,
	/**  Longest losing streak. */
	maxLossStreak: number,
	/**  Sharpe ratio; `null` when undefined for this run. */
	sharpe: number | null,
	/**  Sortino ratio; `null` when undefined for this run. */
	sortino: number | null,
	/**  Entries skipped below the lot step. */
	skippedSubLot: number,
	/**  Entries skipped below minimum notional. */
	skippedSubNotional: number,
	/**  Entries skipped by the leverage cap. */
	skippedLeverageCapped: number,
	/**  The equity curve, rebuilt from the persisted trades. */
	equity: EquityPointDto[],
	/**  The four regimes, always in this fixed order. */
	regimes: RegimeCellDto[],
	/**  The pinned MFE histogram. */
	mfe: HistogramDto,
	/**  The pinned MAE histogram (magnitude). */
	mae: HistogramDto,
	/**  Every persisted trade, in `seq` order, with exact values. */
	trades: TradeRowDto[],
};

/**
 *  What the desktop asks for: one persisted strategy version.
 * 
 *  Pair, timeframes and costs are **not** here. r1's Backtest Lab runs the fixed
 *  BTCUSDT M15+H4 / default-cost request, and a field the product cannot vary would
 *  be a control that does not exist.
 */
export type BacktestRunRequest = {
	/**  The immutable strategy version to run. */
	versionId: string,
};

/**
 *  The single serializable error shape that crosses the Tauri boundary.
 * 
 *  **Four fields, always all present** (r1.s3.w3 added `run_id`; r1.s4.w3's review
 *  added `session_id`), so the TypeScript
 *  type generated from this struct describes every error the frontend can receive and
 *  one rendering path handles all of them. An ordinary error serializes
 *  `run_id: null` — the field is never skipped, because a field that sometimes
 *  vanishes reaches TypeScript as `undefined` while its generated type says
 *  `string | null`.
 */
export type BusError = {
	/**  The family this error came from. */
	code: BusErrorCode,
	/**  The source error's `Display` rendering — prose, safe to show a user. */
	message: string,
	/**
	 *  The id of a backtest run that **is persisted** despite this error
	 *  (r1.s3.w3).
	 * 
	 *  `Some` only when a run was saved and something afterwards could not be read
	 *  back. The message says so too, but a screen must not have to parse prose to
	 *  tell a user "your run is saved, here is its id" — so the id crosses the bus
	 *  as a field. `None` for every other error, including a save that never
	 *  committed: reporting an id for a row that does not exist would be worse than
	 *  reporting none.
	 */
	run_id: string | null,
	/**
	 *  The coaching session this error is ABOUT, when the caller must act on that
	 *  session rather than on the one it asked under.
	 * 
	 *  `Some` on a `Busy` refusal that defers to a turn already running for this
	 *  run — the id being deferred TO. The rail's "Check again" has to reload that
	 *  session, and reloading a freshly minted id instead starts a second billable
	 *  turn, which is the opposite of what a button offering the other turn's
	 *  result promises. The message names it too; the same rule as `run_id` applies,
	 *  that a screen must not parse prose to learn an id it has to act on.
	 */
	session_id: string | null,
};

/**
 *  Which family a [`BusError`] came from — a closed set the frontend can branch on.
 * 
 *  Serializes as a lower-case string discriminant (`"data"`, `"backtest"`, ...), never
 *  as an index, so a variant inserted later cannot renumber the existing ones.
 */
export type BusErrorCode = 
/**  The data pipeline / persistence layer (`DataError`). */
"data" | 
/**  Semantic DSL validation (`ValidationErrors`) — the correctable-rejection family. */
"validation" | 
/**  The backtest engine (`BacktestError`). */
"backtest" | 
/**  Exchange metadata (`ExchangeError`). */
"exchange" | 
/**  The LLM transport (`LlmError`). */
"llm" | 
/**  The composer agent loop (`ComposerError`). */
"composer" | 
/**
 *  An operation the app is **already running** was invoked again (r1.s4.w3,
 *  `pulseai-labs/pulse-trader#141`).
 * 
 *  A family of its own rather than an `Internal`, because it is the one
 *  refusal that is not a fault: nothing broke, nothing failed, and there is
 *  nothing to retry differently — the answer the caller wants is already on
 *  its way from the invocation that holds the key. The coach rail renders it
 *  as "already running" rather than as an error, and it can only do that if
 *  the code says so.
 * 
 *  The discriminant serializes as a string (`"busy"`), so its position
 *  carries no wire meaning; it sits beside the other non-domain code for
 *  readability.
 */
"busy" | 
/**  The shell itself: a dead channel, a failed startup, a bug. Not a domain family. */
"internal";

/**
 *  One event on one run's channel.
 * 
 *  `run_id` + `seq` together let the frontend detect a dropped event rather than
 *  silently rendering a shorter stream.
 */
export type BusEvent = {
	/**  The run this event belongs to — the id the command was invoked with. */
	runId: RunId,
	/**  Monotonic from 0 within a run. */
	seq: number,
	/**  What happened. */
	payload: BusEventPayload,
};

/**
 *  What a streamed event is *about*.
 * 
 *  Internally tagged on `kind`, so the frontend switches on one discriminated union
 *  rather than sniffing which optional fields are present.
 */
export type BusEventPayload = 
/**  The run has begun. Always the first event on a channel. */
{ kind: "started" } | 
/**  Incremental progress — one step, one token, one line of output. */
{ kind: "progress"; 
/**  Human-readable progress text. */
message: string } | 
/**
 *  A composer tool call was dispatched to a builder tool (r1.s1.w4).
 * 
 *  Mirrors [`ComposerEvent::ToolCallStarted`](crate::agent::ComposerEvent):
 *  the payload carries the composer's OWN fields — the tool name and its
 *  non-secret arguments preview — never invented ones. Mapping the composer's
 *  stream onto the channel is rendering, not faking.
 * 
 *  The variant-level `rename_all` exists because the ENUM-level one renames
 *  variants only, not their fields — without it `arguments_preview` would
 *  cross the wire in `snake_case` against the file's `camelCase` convention
 *  (a nothing-word like `message` never exposed this before multi-word
 *  fields).
 */
{ kind: "toolCallStarted"; 
/**  The builder tool the model called (e.g. `add_filter`). */
name: string; 
/**  A short, non-secret preview of the call arguments. */
argumentsPreview: string } | 
/**
 *  A composer tool call produced an outcome (r1.s1.w4).
 * 
 *  Mirrors [`ComposerEvent::ToolCallResult`](crate::agent::ComposerEvent) —
 *  the `Ok` summary or the serialized correctable `FieldError`s, appended to
 *  the same step its `ToolCallStarted` opened.
 */
{ kind: "toolCallResult"; 
/**  The builder tool the model called. */
name: string; 
/**  The `Ok` summary or the serialized correctable errors. */
outcome: string } | 
/**
 *  The run finished successfully. Always the last event on a channel.
 * 
 *  For a compose run (r1.s1.w4) the closing summary is the composer's own
 *  finalize line — `ComposerEvent::Finalized`'s `version_summary`.
 */
{ kind: "finished"; 
/**  A closing summary line. */
message: string };

/**
 *  What the trader did with the coach's proposal.
 * 
 *  Internally tagged on `kind`, so the generated TypeScript is the discriminated
 *  union the rail switches on rather than three optional fields.
 */
export type CoachActionDto = 
/**
 *  Replace the proposal's value with the trader's own edit, and re-validate.
 * 
 *  `new_value` is the value as TEXT — the same exact-string discipline every
 *  other decimal crosses under. Which typed [`ParamValue`] it becomes is decided
 *  by the CURRENT proposal's own parameter kind, not by parsing the string and
 *  guessing: a `"21"` that is a period and a `"21"` that is a threshold are
 *  different mutations, and only the stored proposal knows which leaf this is.
 */
{ kind: "modify"; 
/**  The sweepable leaf being retuned. */
path: string; 
/**  Its new value, as text. */
newValue: string } | 
/**  Record the terminal rejection. No child, no run. */
{ kind: "reject" } | 
/**
 *  Re-apply the current mutation and re-backtest it on the parent's exact
 *  persisted inputs.
 */
{ kind: "accept" };

/**
 *  One turn's cost, in the price table's own billing currency.
 * 
 *  A pair rather than a bare number: the ledger bills in the model's native
 *  currency (CNY for GLM), and an amount with no currency beside it is the kind of
 *  figure a reader silently reads as dollars.
 */
export type CoachCostDto = {
	/**  The exact decimal cost, as a string. */
	amount: string,
	/**  Its billing currency (`"CNY"`). */
	currency: string,
};

/**  The durable result of one decision. */
export type CoachDecisionDto = {
	/**  The session as it now stands. */
	session: CoachSessionDto,
	/**  Present only for a committed accept. */
	accepted: AcceptedCoachDto | null,
};

/**  One decision: which session, and what the trader did. */
export type CoachDecisionRequestDto = {
	/**  The coaching session being decided. */
	sessionId: string,
	/**  What the trader did. */
	action: CoachActionDto,
};

/**  A recorded turn failure and what the trader can do about it. */
export type CoachFailureDto = {
	/**  The typed variant's own `snake_case` tag. */
	kind: string,
	/**  The failure's `Display` rendering — prose, already scrubbed. */
	detail: string,
	/**  The named recovery, chosen by the backend from the typed variant. */
	recovery: string,
};

/**  One recorded coach turn, as the rail shows it. */
export type CoachSessionDto = {
	/**  The session id the desktop minted. */
	sessionId: string,
	/**  The persisted run this turn coached on. */
	runId: string,
	/**  The strategy version whose DSL the proposal mutates. */
	versionId: string,
	/**  `pending` | `proposed` | `failed`. */
	outcome: string,
	/**  The one proposal, when the turn produced one. */
	proposal: ProposalDto | null,
	/**  The one recorded failure, when it did not. */
	failure: CoachFailureDto | null,
	/**  The ledger row this turn produced, if any. */
	llmCallId: string | null,
	/**  That row's recorded cost. */
	cost: CoachCostDto | null,
	/**  That row's recorded prompt version. */
	promptVersion: string | null,
	/**  When the turn was claimed (RFC3339 UTC). */
	createdAt: string,
};

/**
 *  What the rail asks for when the trader presses "Ask the coach", and again on
 *  every reload.
 * 
 *  **The DESKTOP mints the session id** (a UUID) and passes the same one back
 *  forever after; the backend never mints one. That is what makes a reload
 *  idempotent rather than a second billable turn: the id is the key the durable
 *  session is stored under, and only the caller that owns the screen knows whether
 *  this is a new ask or the same one being looked at again.
 */
export type CoachTurnRequestDto = {
	/**  The persisted backtest run to coach on. */
	runId: string,
	/**  The session id this turn is recorded under — minted by the desktop. */
	sessionId: string,
};

/**
 *  The compact DSL summary a finalized run returns — the finalize summary
 *  card's data, rendered from the fields the persisted version actually
 *  carries (the `w3` "real fields" discipline: render what the DSL carries,
 *  omit what it does not).
 * 
 *  Lines, not structures, on purpose: the ring renders the DSL's own values
 *  into mono summary lines and the screen never parses strategy JSON.
 */
export type ComposeDslSummary = {
	/**  The trade side, `"long"` / `"short"` — the DSL's own `Direction` value. */
	direction: string,
	/**  The required entry trigger, e.g. `rsi(14) < 30`. */
	entry: string,
	/**  The gating conditions conjoined with the entry, one line each. */
	filters: string[],
	/**  The exit rules, one line each (e.g. `stop_loss 5%`, `take_profit 2R`). */
	exits: string[],
	/**  The risk / sizing inputs, one line each. */
	risk: string[],
};

/**
 *  The outcome of one compose run — [`StreamOutcome`]'s shape (a run id, what
 *  actually crossed, cancellation) extended with the finalize payload.
 * 
 *  `strategy` is `None` exactly when the run did not finalize: a cancelled run
 *  (the screen went away) carries no summary because nothing persisted.
 */
export type ComposeResult = {
	/**  The run this outcome describes. */
	runId: RunId,
	/**  How many events actually reached the far end. */
	emitted: number,
	/**  True when the far end went away mid-run (the screen unmounted). */
	cancelled: boolean,
	/**  The persisted strategy summary — present iff the run finalized. */
	strategy: ComposeStrategySummary | null,
};

/**  What a finalized compose run reports about the strategy it persisted. */
export type ComposeStrategySummary = {
	/**  The persisted strategy's repo-minted id. */
	strategyId: string,
	/**  The strategy's name (the DSL's own `name`). */
	strategyName: string,
	/**  The persisted initial version's repo-minted id. */
	versionId: string,
	/**
	 *  Who authored the version — the `strategy_version.created_by` label
	 *  (`"composer_llm"` for this run; the pinned serialization strings).
	 */
	createdBy: string,
	/**  How many `LlmCall`s produced this version (its provenance count). */
	llmCallCount: number,
	/**  The compact DSL summary rendered above. */
	dsl: ComposeDslSummary,
};

/**
 *  The value-free credential read for a UI banner (r1.s1.w2 step 6) — which source
 *  answered, or that none did.
 * 
 *  This is the seam `r1.s1.w5` renders its no-credential banner from. It carries no
 *  key material at all, so it is safe to send across the Tauri IPC boundary, and it
 *  is computed without performing any LLM request.
 * 
 *  `specta::Type` (r1.s1.w5): this is the one domain type that crosses the Tauri
 *  boundary directly rather than through a `src/tauri/`-ring wire type — it already IS
 *  the value-free wire shape the banner needs, so a wrapper struct would add a
 *  translation step with nothing to translate.
 */
export type CredentialStatus = 
/**  The process environment answered. */
"env" | 
/**  `$PULSE_CONFIG_DIR/.env` answered. */
"config-dir" | 
/**  A working-directory / manifest-directory `.env` answered. */
"cwd-dotenv" | 
/**  The application data directory's `.env` answered. */
"app-data-dir" | 
/**
 *  No usable credential — absent everywhere, or found but REFUSED by the
 *  permission checks. Both read as "not usable", which is what a banner needs.
 */
"none";

/**
 *  A version's DSL rendered to summary lines — exactly the fields
 *  [`StrategyDsl`] carries, nothing more.
 */
export type DslSummary = {
	/**  The document's name. */
	name: string,
	/**  `"long"` or `"short"`. */
	direction: string,
	/**  The entry trigger, one line (the DSL's `entry` is a single condition). */
	entry: string[],
	/**  The gating filters, one line each. */
	filters: string[],
	/**  The exit rules, one line each. */
	exits: string[],
	/**  The risk parameters, one line each. */
	risk: string[],
};

/**  One point on the reconstructed equity curve. */
export type EquityPointDto = {
	/**  Epoch milliseconds, exact integer string. */
	timeMs: string,
	/**  Account equity at that point, exact decimal string. */
	equity: string,
};

/**  One `[lower, upper)` histogram bin and its count. */
export type HistogramBinDto = {
	/**  Inclusive lower bound in R, exact decimal string. */
	lower: string,
	/**  Exclusive upper bound in R, exact decimal string. */
	upper: string,
	/**  How many trades landed in this bin. */
	count: number,
};

/**  A pinned excursion histogram, ready to render without further analysis. */
export type HistogramDto = {
	/**  The shared bin width in R, exact decimal string (`"0.25"`). */
	binWidth: string,
	/**  The finite bins, ascending, covering `[0, 3)`. */
	bins: HistogramBinDto[],
	/**  Normalized values below `0` — a sign violation, counted rather than hidden. */
	underflow: number,
	/**  Normalized values at or above `3R`. */
	overflow: number,
};

/**
 *  The `library_overview` command's whole payload: every strategy, each with its
 *  version tree.
 */
export type LibraryOverview = {
	/**  Every persisted strategy, in the repository's list order. */
	strategies: LibraryStrategy[],
};

/**  One row of a version's run catalog (`list_runs_for_version`'s projection). */
export type LibraryRunSummary = {
	/**  The run's id. */
	id: string,
	/**  Run timestamp (RFC3339 UTC, from the record). */
	createdAt: string,
	/**  Mean P&L per trade, e.g. `"+0.42R"`. */
	expectancy: string,
	/**  Completed trades in the run. */
	trades: number,
};

/**  One strategy and its `version_tree`-ordered versions. */
export type LibraryStrategy = {
	/**  The strategy's id. */
	id: string,
	/**  The strategy's name. */
	name: string,
	/**  Creation timestamp (RFC3339 UTC, from the record). */
	createdAt: string,
	/**  The pinned version's id, if the strategy has one (FR-11 pin). */
	pinnedVersionId: string | null,
	/**  All versions, parent-before-child (`version_tree` order). */
	versions: LibraryVersion[],
};

/**  One version: tree position, DSL summary, stats-or-em-dash, recent runs. */
export type LibraryVersion = {
	/**  The version's id. */
	id: string,
	/**  The parent version's id (`None` for a root). */
	parentId: string | null,
	/**  Creation timestamp (RFC3339 UTC, from the record). */
	createdAt: string,
	/**  The version's DSL, rendered to summary lines. */
	dsl: DslSummary,
	/**
	 *  The latest persisted run's stats, or `None` when no run exists — the
	 *  screen renders an em dash on `None` (grill A1).
	 */
	stats: VersionStats | null,
	/**
	 *  The expectancy delta vs the parent's, formatted (e.g. `"+0.12R"`), when
	 *  BOTH this version and its parent carry a run. `None` otherwise.
	 */
	deltaVsParent: string | null,
	/**
	 *  This version's run catalog (best-effort — one corrupt row costs its row
	 *  here, not the screen), newest first.
	 */
	recentRuns: LibraryRunSummary[],
};

/**  The proposed change: one path, one value. */
export type MutationDto = {
	/**  The sweepable leaf's locator. */
	path: string,
	/**  The value to write there, as an exact string. */
	newValue: string,
};

/**  The coach's single proposal, as the rail's card renders it. */
export type ProposalDto = {
	/**  The one change. */
	mutation: MutationDto,
	/**  Why the coach believes it helps. */
	hypothesis: string,
	/**  Where the proposal stands. */
	disposition: string,
	/**  The child version an accept minted. */
	childVersionId: string | null,
	/**  The re-backtest run of that child. */
	acceptedRunId: string | null,
	/**  The latest accept attempt's typed failure, if it failed. */
	acceptFailure: AcceptFailureDto | null,
};

/**
 *  Whether the committed child run could be read back.
 * 
 *  Untagged so the wire shape is exactly `"ok" | { failure }`: past the commit the
 *  accept has SUCCEEDED, so this is not an error family — it is a note about what
 *  this process could re-read, and the rail says so beside two real ids.
 */
export type ReadBackDto = 
/**  The child run read back. Serializes as the bare string `"ok"`. */
ReadBackOk | 
/**  It did not — the accept still committed. */
{ 
/**  Why the read back failed. */
failure: string };

/**  The `"ok"` token of [`ReadBackDto`]. */
export type ReadBackOk = 
/**  The one value. */
"ok";

/**  One regime's persisted trade count and net P&L. */
export type RegimeCellDto = {
	/**  `trending_up` / `trending_down` / `ranging` / `unknown`. */
	regime: string,
	/**  Trades that opened in this regime. */
	tradeCount: number,
	/**  Net P&L across them, exact decimal string. */
	netPnl: string,
};

/**
 *  A per-invocation run identifier, minted when a streaming command starts.
 * 
 *  Opaque on the wire (`#[serde(transparent)]` over a UUID string) so the frontend
 *  compares it and never parses it.
 */
export type RunId = string;

/**
 *  The metadata the placeholder page renders — the one round-trip command this work
 *  item ships.
 * 
 *  Deliberately boring: no credential and no LLM-derived data crosses this boundary, so
 *  no risk gate fires on this item. `r1.s1.w4` is where that changes and it carries the
 *  controls.
 */
export type ShellInfo = {
	/**  The crate version this bundle was built from. */
	appVersion: string,
	/**  The build-time `engine_fingerprint` (FR-7) — proves the GUI and CLI share one core. */
	engineFingerprint: string,
	/**  The compiled target triple. */
	targetTriple: string,
	/**  How many strategies the database holds — a real read through managed state. */
	strategyCount: number,
};

/**  How a streaming run ended. */
export type StreamOutcome = {
	/**  The run this outcome describes. */
	runId: RunId,
	/**  How many events actually reached the far end. */
	emitted: number,
	/**  True when the far end went away mid-run (the screen unmounted). */
	cancelled: boolean,
};

/**
 *  One persisted run summary, every money value an exact string.
 * 
 *  `sharpe`/`sortino` stay nullable numbers for the reason
 *  [`BacktestRunDto`](super::backtest::BacktestRunDto) keeps them so: they are
 *  genuinely `f64`-derived, and `null` is already how "not enough trades to
 *  compute" is spelled everywhere else.
 */
export type SummaryDto = {
	/**  Completed trades. */
	tradeCount: number,
	/**  How many won. */
	winCount: number,
	/**  How many lost. */
	lossCount: number,
	/**  Fraction of trades that won. */
	winRate: string,
	/**  Sum of winning P&L. */
	grossProfit: string,
	/**  Sum of losing P&L magnitudes. */
	grossLoss: string,
	/**  Net P&L. */
	netPnl: string,
	/**  Gross profit over gross loss; `null` when there is no loss to divide by. */
	profitFactor: string | null,
	/**  Mean winning trade. */
	avgWin: string,
	/**  Mean losing trade. */
	avgLoss: string,
	/**  Mean P&L per trade — the rail's headline comparison. */
	expectancy: string,
	/**  Largest peak-to-trough equity drop. */
	maxDrawdown: string,
	/**  Longest winning streak. */
	maxWinStreak: number,
	/**  Longest losing streak. */
	maxLossStreak: number,
	/**  Total taker commission. */
	commissionTotal: string,
	/**  Total signed funding. */
	fundingTotal: string,
	/**  Sharpe ratio; `null` when undefined for this run. */
	sharpe: number | null,
	/**  Sortino ratio; `null` when undefined for this run. */
	sortino: number | null,
};

/**  One persisted trade, exactly as stored. */
export type TradeRowDto = {
	/**  `long` / `short`. */
	direction: string,
	/**  Position size, exact decimal string. */
	qty: string,
	/**  Entry fill price. */
	entryPrice: string,
	/**  Exit fill price. */
	exitPrice: string,
	/**  Epoch ms the entry signalled. */
	entrySignalTime: string,
	/**  Epoch ms the entry filled. */
	entryFillTime: string,
	/**  Epoch ms the exit signalled. */
	exitSignalTime: string,
	/**  Epoch ms the exit filled. */
	exitFillTime: string,
	/**  Taker fees on this trade. */
	feesTotal: string,
	/**  Signed funding on this trade. */
	fundingTotal: string,
	/**  Adverse slippage cost. */
	slippageTotal: string,
	/**  Realized P&L. */
	realizedPnl: string,
	/**  Realized R multiple. */
	realizedR: string,
	/**  Maximum favourable excursion, in R — exact, unbinned. */
	mfeR: string,
	/**  Maximum adverse excursion, in R — exact, unbinned, sign preserved. */
	maeR: string,
	/**  Why the trade closed. */
	exitReason: string,
	/**  What opened it. */
	source: string,
	/**  The regime at entry. */
	regime: string,
};

/**
 *  The three headline KPIs the screen renders per version, pre-formatted from
 *  the persisted run's [`SummaryStats`].
 */
export type VersionStats = {
	/**  Mean P&L per trade, e.g. `"+0.42R"`. */
	expectancy: string,
	/**  Fraction of winners, e.g. `"48.3%"`. */
	winRate: string,
	/**  Completed trades in the run. */
	trades: number,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

